### ISSUE TITLE
Fix generation of charts touching the international date line.

### ISSUE THREAD

**Issue by ehrenfeu** [OpenSeaMap/garmin#3]
Currently a "550 Failed to change directory" error is shown when trying to download one of these [garmin charts](http://wiki.openstreetmap.org/wiki/OpenSeaMap_and_Garmin_nautical_chart_plotter):

* Pacific Equatorial West	
* Pacific Equatorial East	
* Pacific South
* Tasman Sea

According to Christian, these charts actually fail to build, probably related to the IDL (international date line).

A new build script that cuts the charts off at the date line is waiting to be implemented.

**Comment by zenfunk** [comment]
I guess the issue has been resolved. All the maps seem to build now. I suggest closing of the bug.

**Comment by ehrenfeu** [comment]
Agreed. Closing the issue. Thanks for the hint @zenfunk!
